### ISSUE TITLE
consider deleting the #[deny(unsafe_code)] in lib.rs

### ISSUE THREAD

**Issue by vlmutolo** [jneem/imbl#24]
As seen [here](https://github.com/jneem/imbl/blob/1818ef61388807cc03fcb97af43013a265d3d97e/src/lib.rs#L334), `src/lib.rs` currently contains the following line.

```rust
#![deny(unsafe_code, nonstandard_style)]
```

However, `imbl` (as a fork of [`im`](https://github.com/bodil/im-rs)) makes frequent use of `#[allow(unsafe_code)]`. A quick `rg -cF '#[allow(unsafe_code)]'` reveals the following 24 instances of allowed unsafe code throughout the library.

```
src/vector/focus.rs:7
src/vector/mod.rs:8
src/nodes/hamt.rs:5
src/nodes/btree.rs:3
src/util.rs:1
```

I think it's a little misleading to have the `deny(unsafe_code)` when we just go ahead and `allow(unsafe_code)` wherever we need it. It also adds a small development burden to have to add `allow(unsafe_code)` if you want/need to use `unsafe`.

**Comment by jneem** [comment]
Good point. My current understanding (which I will check more carefully) is that the existing unsafe code is in support of the "pool" feature, which doesn't currently exist in `imbl` but I don't want to just delete all of the code that's involved because I want to keep the possibility of resurrecting it. I'll see if we can do something like `#[cfg(pool, deny(unsafe_code))]` for now, and have an officially documented policy for unsafe...

**Comment by vlmutolo** [comment]
Interesting. I wonder if it would be better, in that case, to do `#[cfg(pool, allow(unsafe_code))]` on each individual usage of `unsafe`. That way, the allows would be restricted to just blocks related to the `pool` feature, instead of the `pool` feature enabling `unsafe` usage anywhere in the code base.

**Comment by jneem** [comment]
Ah, sorry, there was a typo in my previous comment. I meant something more like a global `#![cfg_attr(not(feature = "pool), deny(unsafe_code))]`. I didn't test this particular invocation, but the intention was that we adopt a policy like "unsafe code is only allowed when the `pool` feature is enabled", and then we enforce this policy with a single global declaration. You'd already convinced me that we don't want lots of additional ceremony around every `unsafe` block.

**Comment by jneem** [comment]
Ok, it's a little more complicated than just "unsafe code is only for pool". For example, I think `swap_indices` is unsound, because it makes assumptions about the `IndexMut` implementation (which is sort of ok because it isn't public and it's only used in an ok way, but still...)
