### ISSUE TITLE
Is Clone necessary for the Debug implementation of Vector?

### ISSUE THREAD

**Issue by wsx-ucb** [jneem/imbl#25]
Hello, I'm wondering if the trait bound `A: Clone` when implementing `Debug` for `Vector<A>` is necessary. https://github.com/jneem/imbl/blob/3fd258cee59499cac0243822903497c83fb00e6a/src/vector/mod.rs#L1784
Previously those bounds are removed for maps and sets (see https://github.com/bodil/im-rs/issues/81).
Can the same thing be done to `Vector`?

**Comment by jneem** [comment]
I agree that we can relax the bounds, so I guess we may as well. Is there really a use for it, though? In order to insert anything into ` Vector<A>`, you need `A: Clone`...

**Comment by wsx-ucb** [comment]
You are right that basic operation like insertion needs `A: Clone`, so most likely the specific instances used already satisfies the constraint. But let's say we want to define another generic data structure based on `Vector`, then we are forced to include the `Clone` constraint on all implementation of it, and this will keep rippling out... So for code cleanness, I hope the trait constraint can be kept minimal.

**Comment by nomad010** [comment]
I think the recommendation that was somewhere in the old docs (I think) was to use Vector<Rc<NonCloneThing>>, that way you don't need to litter Clone in cases where it isn't strictly necessary.

I also tried to implement what you wanted in my experimental RRB implementation (for cleanliness) and unfortunately it didn't pan out. You needed to write 1 implementation of insert for Clone things and 1 for non-Clone things which you can't do in stable Rust AFAIK.

**Comment by jneem** [comment]
My understanding was that `insert` (and any other function that modifies the `Vector`) would require `A: Clone`, but the read-only methods shouldn't need to.

**Comment by nomad010** [comment]
Ah yes, sorry you are correct, the read-only methods wouldn't need them. It is also possible (or should be possible I think) to construct an `empty` or `singleton` `Vector` without Clone.
