### ISSUE TITLE
Unnecessary trait bounds in Vector's implementation

### ISSUE THREAD

**Issue by wsx-ucb** [jneem/imbl#26]
This may be a more general issue than #25.
The [methods implemented](https://docs.rs/im/15.0.0/im/vector/struct.Vector.html#implementations) for `Vector<A>` always have the `A: Clone` attached, even for methods like `len()`. This further affects all the [trait implementations](https://docs.rs/imbl/1.0.1/imbl/vector/struct.Vector.html#trait-implementations).

Can the API be refactored into a less restrictive one?

**Comment by jneem** [comment]
Closed by #32.
