### ISSUE TITLE
OrdSet cannot contain different objects which have equal ordering

### ISSUE THREAD

**Issue by ImJeremyHe** [jneem/imbl#30]
```
#[derive(Debug, Clone, Hash, PartialEq, Eq)]
pub struct Node {
    pub ord: u32,
    pub id: u32,
}

impl PartialOrd for Node {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for Node {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.ord.cmp(&other.ord)
    }
}

fn main() {
    use imbl::ordset::OrdSet;
    let mut s = OrdSet::<Node>::new();
    s.insert(Node { ord: 2, id: 1 });
    s.insert(Node { ord: 2, id: 2 });
    println!("{:?}", s.len()); // 1
}

```
The output is 1.

**Comment by jneem** [comment]
This is the correct behavior, in my opinion:
- the standard library's `BTreeSet` has the same behavior ([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=cd51670086b2174c1b2076e0e08c3e11))
- the documentation for [`PartialOrd`](https://doc.rust-lang.org/std/cmp/trait.PartialOrd.html) requires that "`a == b` if and only if `partial_cmp(a, b) == Some(Equal)`", and so this implementation of `PartialOrd` doesn't satisfy the trait's requirements.

**Comment by ImJeremyHe** [comment]
Thanks!
