### ISSUE TITLE
Try to take over `im` instead

### ISSUE THREAD

**Issue by elliot-u410** [jneem/imbl#47]
Seems like it would be ideal to just take over `im`. I'm assuming you've already tried, but it seems worth keeping that as an ideal goal.

**Comment by jneem** [comment]
I may at some point, but there are a couple of reasons I haven't done it yet:
- I wasn't a contributor to `im`, so there's no reason for the maintainer to trust me.
- I don't want to take on more than I'm capable of, and forking allows me to drop things, like the `Rc` version and the memory pools.

**Comment by criloz** [comment]
@jneem just curious, why the `Rc` version is dropped on imbl?

**Comment by jneem** [comment]
I just wasn't up to taking on the extra maintenance. The `Rc` version is a bit complicated, involving some code generation.

Actually, now that GATs are stabilized it might be possible to use them instead of code generation. I haven't tried it, though.
