### ISSUE TITLE
Moving to sized-chunks-0.7

### ISSUE THREAD

**Issue by dfoxfranke** [jneem/imbl#68]
I'm working on a crate that has a transitive dependency on `sized_chunks`, by way of `im` and then by my own `im-rope` crate. I'm currently having some trouble with pathological compilation times and with having to bump `recursion_limit` quite a bit in order to compile at all. I currently believe that the root of the second problem (medium-high confidence), and possibly the first as well (low-medium confidence), is the type system hackery used in `sized-chunks-0.6` for encoding natural numbers at the type level. `sized-chunks-0.7` does away with all that code in favor of const generics. I'd like to try getting sized-chunks upgraded to 0.7 and see if my problems go away. How difficult do think it would be to rebase `imbl-sized-chunks` against 0.7 and then upgrade `imbl` to depend on it?

**Comment by jneem** [comment]
I may have misunderstood (please re-open if so), but `imbl-sized-chunks` has never used the type-level natural number trickery -- it was forked from `sized-chunks` somewhere between 0.6 and 0.7, after the const generic support was added.

**Comment by dfoxfranke** [comment]
Oh, good! Sorry, I only looked as far as seeing it was forked from a 0.6 version number.

**Comment by dfoxfranke** [comment]
And sure enough, that got me a big improvement in compilation times. I still need to raise the default recursion limit but not as much.

**Comment by jneem** [comment]
Thanks for trying and reporting back!
