### ISSUE TITLE
OrdMap::range returns an ExactSizeIterator with the wrong size hint

### ISSUE THREAD

**Issue by goffrie** [jneem/imbl#84]
Sample code:

```rust
use imbl::OrdMap;

fn main() {
    let mut map = OrdMap::new();
    map.insert(1, "one");
    map.insert(2, "two");
    map.insert(5, "five");
    let iter = map.range(2..5);
    println!("{}", iter.len()); // prints 3
    println!("{:?}", iter.collect::<Vec<_>>()) // prints [(2, "two")]
}
```

`OrdMap::range` returns an iterator that claims to know the number of items it will iterate over, but it just uses `self.size` which is the size of the entire map. This causes `size_hint` to return the wrong value (in this case `(3, Some(3))`). Furthermore, `Iter` implements `ExactSizeIterator` which is also wrong in this case.

`OrdMap::range` should probably return a different iterator wrapper. I notice the underlying RangedIter implements a conservative `size_hint` that returns `(0, None)` (it could probably return `(0, Some(self.remaining))` though).

**Comment by jneem** [comment]
Thanks! I made a PR that returns a new wrapper, which I agree looks like the way to go. Unfortunately I don't know a way to do this without also breaking backwards compatibility, so I guess I'll need to release a new major version.

I don't know the reason for the conservative `size_hint`; I looked through `git blame` but it didn't help. Fuzz tests seem to pass when replacing the upper bound with `Some(self.remaining)`, so I'll make that change too.
